config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root :to => "shop/starts#index"

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account

    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    put '/add_money' => 'accounts#add_money', as: :add_money
    post 'ticket_return' => '/authors/tickets#ticket_return', as: :ticket_return
    post '/tickets/summary' => 'tickets#buy', as: :summary
    post '/buy' => 'tickets#index', as: :buy
    post '/return_all' => '/authors/tickets#return_all', as: :return_all
    get '/returns' => 'tickets#returns', as: :returns
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
    resources :tickets
    resources :starts
    resources :events
  end

  scope module: 'shop' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'starts' => 'starts#index', as: :starts
    get 'events' => 'events#index', as: :events
    get 'events/:id' => 'events#show', as: :event
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :tickets

  validates_presence_of :name, on: :update

  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end

  def gravatar_image_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      "Moje konto"
    end
  end

  private

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id            :integer          not null, primary key
#  name          :string
#  seat_id_seq   :string
#  address       :text
#  price         :decimal(, )
#  email_address :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  picture_url   :string
#

class Ticket < ApplicationRecord

  scope :most_recent, -> { order(id: :desc)}
  belongs_to :author, :optional => true
  belongs_to :event

end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index                               
      @posts = Post.all
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
  end


end

app/controllers/author/tickets_controller.rb
module Author
  class TicketsController < AuthorController
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]

    # GET /tickets
    # GET /tickets.json
    def index
      @tickets = Ticket.most_recent
    end

    # GET /tickets/1
    # GET /tickets/1.json
    def show
    end

    # GET /tickets/new
    def new
      @ticket = Ticket.new
    end

    # GET /tickets/1/edit
    def edit
    end

    # POST /tickets
    # POST /tickets.json
    def create
      @ticket = Ticket.new(ticket_params)

      respond_to do |format|
        if @ticket.save
          format.html {redirect_to @ticket, notice: 'Ticket was successfully created.'}
          format.json {render :show, status: :created, location: @ticket}
        else
          format.html {render :new}
          format.json {render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /tickets/1
    # PATCH/PUT /tickets/1.json
    def update
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html {redirect_to @ticket, notice: 'Ticket was successfully updated.'}
          format.json {render :show, status: :ok, location: @ticket}
        else
          format.html {render :edit}
          format.json {render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /tickets/1
    # DELETE /tickets/1.json
    def destroy
      @ticket.destroy
      respond_to do |format|
        format.html {redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :picture_url)
    end
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  before_action :authenticate_author!
  before_action :ensure_admin_user!

  def ensure_admin_user!
    if !current_author.admin? and (request.path.start_with?('/authors/posts') or request.path.start_with?('/authors/starts') or request.path.start_with?('/authors/events'))
      redirect_to root_path
    end
  end
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit

    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully saved info.'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end

    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password.'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current password was incorrect.'
      end
      redirect_to authors_account_path
    end

    def add_money
      amount = params[:amount]
      author = current_author
      author.money = author.money + Integer(amount)
      author.save()
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:name, :email, :bio, :birth_date)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
  end
end

app/controllers/authors/events_controller.rb
module Authors
  class EventsController < AuthorController
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    # GET /events.json
    def index
      @events = Event.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /events/1
    # GET /events/1.json
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully created.'}
          format.json {render :show, status: :created, location: @event}
        else
          format.html {render :new}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully updated.'}
          format.json {render :show, status: :ok, location: @event}
        else
          format.html {render :edit}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html {redirect_to authors_event_path, notice: 'Event was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :address, :price, :description, :date, :quantity , :event_picture_url, :adult, :tag_list)
    end
  end


end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html {redirect_to authors_post_path(@post), notice: 'Post was successfully created.'}
          format.json {render :show, status: :created, location: @post}
        else
          format.html {render :new}
          format.json {render json: @post.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html {redirect_to authors_post_path(@post), notice: 'Post was successfully updated.'}
          format.json {render :show, status: :ok, location: @post}
        else
          format.html {render :edit}
          format.json {render json: @post.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html {redirect_to authors_post_path, notice: 'Post was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
    end
  end


end

app/controllers/authors/starts_controller.rb
module Authors
  class StartsController < AuthorController
    before_action :set_start, only: [:show, :edit, :update, :destroy]

    # GET /starts
    # GET /starts.json
    def index
      @starts = Start.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /starts/1
    # GET /starts/1.json
    def show
    end

    # GET /starts/new
    def new
      @start = Start.new
    end

    # GET /starts/1/edit
    def edit
    end

    # POST /starts
    # POST /starts.json
    def create
      @start = Start.new(start_params)

      respond_to do |format|
        if @start.save
          format.html {redirect_to authors_start_path(@start), notice: 'Post was successfully created.'}
          format.json {render :show, status: :created, location: @start}
        else
          format.html {render :new}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /starts/1
    # PATCH/PUT /starts/1.json
    def update
      respond_to do |format|
        if @start.update(start_params)
          format.html {redirect_to authors_start_path(@start), notice: 'Start was successfully updated.'}
          format.json {render :show, status: :ok, location: @start}
        else
          format.html {render :edit}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /starts/1
    # DELETE /starts/1.json
    def destroy
      @start.destroy
      respond_to do |format|
        format.html {redirect_to authors_start_path, notice: 'Start was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_start
      @start = Start.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def start_params
      params.require(:start).permit(:picture_url, :title, :features)
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/authors/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url, id: :ticket_picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/tickets/_return.html.erb
<tr>
  <td><%= r.name %> </td>
  <td><%= r.price %></td>
  <td><%= r.return_counter %></td>
  <td><%= r.date %></td>
  <td><%= r.author_id %></td>
  <td><%= button_to 'Akceptuj', authors_return_all_path, params: {event_price: r.price, event_id: r.event_id, author_id: r.author_id, ticket_counter: r.ticket_counter, ticket_id: r.id, date: r.date, return_counter: r.return_counter}, method: :post, class: "btn btn-warning btn-pointer" %></td>
</tr>

app/views/authors/tickets/_ticket.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= link_to event_url(ticket.event_id) do %>
      <div class="card-topper" style='background-image: url(<%= ticket.picture_url %>);'></div>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to ticket.name, event_url(ticket.event_id) %></h4>
      <h6 class="published-date">Posiadane bilety: <%= ticket.ticket_counter %></h6>
      <h6 class="published-date">Zwrócone bilety: <%= ticket.return_counter %></h6>
      <p class="card-text">Aby, zwrócić bilet nacisnij poniższy, przycisk. Następnie oczekuj na akceptacje zwrotu przez
        administracje witryny. </p>
      <% if ticket.ticket_counter > 0 %>
        <%= button_to 'Zwróć bilet', authors_ticket_return_path, params: {body: 'super test', event_id: ticket.event_id, author_id: ticket.author_id, ticket_counter: ticket.ticket_counter, ticket_id: ticket.id}, method: :post, class: "btn btn-danger" %>
      <% else %>
        <button class="btn btn-danger" disabled="true">Nie możesz już zwracać biletów</button>
      <% end %>
    </div>
  </div>
</div>

app/views/authors/tickets/buy.html.erb
<% provide(:page_title, "Kup bilet") %>
<% provide(:events_active, 'active') %>

<div class="row">
  <div class="col-md-9">
    <div class="row">
      <h1>Kupujesz bilet na wydarzenie - <span class="ticket-title"><%= params[:event_name] %></span></h1>
    </div>
    <div class="row">
      <h3>Miejsce - <%= params[:event_address] %></h3>
    </div>
    <div class="row">
      <h3>Data - <%= I18n.l params[:event_date].to_time, :format => "%d-%m-%Y %H:%M" %></h3>
    </div>
    <div class="row">
      <h3>Ilości - <%= params[:ticket_counter] %> szt.</h3>
    </div>
  </div>
  <div class="col-md-3">
    <img class="img-fluid" src=<%= params[:event_picture] %>/>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="row">
      <h3>Twoje środki</h3>
    </div>
    <div class="row">
      <%= number_to_currency(current_author.money, unit: "zł", separator: ",", delimiter: "", format: "%n %u") %>
    </div>
    <div class="row">
      <h3>Koszt biletów</h3>
    </div>
    <div class="row">
      <% if (I18n.l params[:event_date].to_date, :format => "%Y-%m-%d").to_s == Date.current.to_s %>
        <%
          @today_price = (params[:event_price].to_f * 1.2)
          @sum_price = @today_price * params[:ticket_counter].to_i
        %>
        <span> <%= params[:ticket_counter].to_s + ' szt. x ' + number_to_currency(@today_price,
                                                                                  unit: "zł", separator: ",", delimiter: "", format: "%n %u").to_s + ' = ' %>
          <%= number_to_currency(@sum_price,
                                 unit: "zł", separator: ",", delimiter: "", format: "%n %u") %></span>
      <% else %>
        <%
          @today_price = params[:event_price].to_f
          @sum_price = @today_price * params[:ticket_counter].to_i
        %>
        <span><%= params[:ticket_counter].to_s + ' x ' + @today_price.to_s + ' = ' %><%= number_to_currency(@sum_price,
                                                                                                            unit: "zł", separator: ",", delimiter: "", format: "%n %u") %></span>
      <% end %>
    </div>
    <div class="row">
      <% if (current_author.money - @sum_price) >= 0 %>
        <div class="col-md-12">
          <%= button_to 'Kup bilety', authors_tickets_path,
                        params: {event_id: params[:event_id], user_id: params[:user_id], ticket_counter: params[:ticket_counter]}, method: :post, class: "btn btn-success btn-pointer btn-max" %>

        </div>

      <% else %>
        <div class="col-md-12">
          <%= link_to 'Doładuj konto', authors_account_path, class: "btn btn-warning btn-pointer btn-max" %>
        </div>
      <% end %>

    </div>
  </div>
  <div class="col-md-8">
    <div class="row">
      <h3>Opis</h3>
    </div>
    <div class="row">
      <p class="ticket-description"><%= params[:event_description] %></p>
    </div>
  </div>
</div>


<div class="row">

  <span>Event id: <%= params[:event_id] %></span>


  <span>Event ticket counter: </span>
  <span>Current author: <%= params[:user_id] %></span>


</div>

app/views/authors/tickets/edit.html.erb
<% provide(:page_title, "Edytuj #{@ticket.name}") %>
<% provide(:ticket_active, 'active') %>

<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', authors_tickets_path %>

app/views/authors/tickets/index.html.erb
<% provide(:page_title, 'Twoje Bilety') %>
<% provide(:tickets_active, 'active') %>

<p id="notice"><%= notice %></p>

<div class="row">
  <h1>Twoje bilety</h1>
</div>

<div class="row">
  <% if @tickets.length != 0 %>
    <% @tickets.each do |ticket| %>
      <%= render ticket %>
    <% end %>
  <% else %>
    <h2>Brak zakupionych biletów</h2>
  <% end %>
</div>
<div class="apple_pagination">
  <div class="col-xl-12">
    <%= will_paginate @tickets, container: false %>
  </div>
</div>

app/views/authors/tickets/new.html.erb
<% provide(:page_title, 'Dodaj nowe wydarzenie') %>
<% provide(:tickets_active, 'active') %>

<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', authors_tickets_path %>

app/views/authors/tickets/returns.html.erb
<% provide(:page_title, "Zwroty biletów") %>
<% provide(:author_returns_active, 'active') %>

<div class="row">
  <h2>Zwroty biletów na wydarzenia</h2>
</div>
<div class="row">
  <% if @returns != nil %>
    <table class="table table-striped">
      <tr>
        <th colspan="1">
          Tytuł
        </th>
        <th>
          Kwota
        </th>
        <th>
          Ilość
        </th>
        <th>
          Data
        </th>
        <th>
          Author ID
        </th>
        <th>
        </th>
      </tr>
      <% @returns.each do |r| %>
        <%= render :partial => 'return', :locals => {:r => r} %>
      <% end %>
    </table>
  <% else %>
    <h3>Brak zwrotów biletów</h3>
  <% end %>
</div>

app/views/authors/tickets/show.html.erb
<% provide(:page_title, @ticket.name) %>
<% provide(:tickets_active, 'active') %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Picture URL:</strong>
  <%= @ticket.picture_url %>
</p>

<%= link_to 'Edit', edit_authors_ticket_path(@ticket) %> |
<%= link_to 'Back', authors_tickets_path %>