config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root :to => "shop/starts#index"

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account

    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    put '/add_money' => 'accounts#add_money', as: :add_money
    post 'ticket_return' => '/authors/tickets#ticket_return', as: :ticket_return
    post '/tickets/summary' => 'tickets#buy', as: :summary
    post '/buy' => 'tickets#index', as: :buy
    post '/return_all' => '/authors/tickets#return_all', as: :return_all
    get '/returns' => 'tickets#returns', as: :returns
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
    resources :tickets
    resources :starts
    resources :events
  end

  scope module: 'shop' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'starts' => 'starts#index', as: :starts
    get 'events' => 'events#index', as: :events
    get 'events/:id' => 'events#show', as: :event
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  PER_PAGE = 3
  has_many :tickets

  scope :soon, -> {where("date >= '#{Date.today}'").order(date: :asc)}
  scope :archive, -> {where("date < '#{Date.today}'").order(date: :asc)}

  scope :recent_paginated, -> (page) { soon.paginate(page: page, per_page: PER_PAGE) }

  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  scope :archive_paginated, -> (page) { archive.paginate(page: page, per_page: PER_PAGE) }
  scope :archive_for, -> (page, tag) do
    archive_paginated(page).with_tag(tag)
  end
end

app/controllers/authors/events_controller.rb
module Authors
  class EventsController < AuthorController
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    # GET /events.json
    def index
      @events = Event.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /events/1
    # GET /events/1.json
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully created.'}
          format.json {render :show, status: :created, location: @event}
        else
          format.html {render :new}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully updated.'}
          format.json {render :show, status: :ok, location: @event}
        else
          format.html {render :edit}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html {redirect_to authors_event_path, notice: 'Event was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :address, :price, :description, :date, :quantity , :event_picture_url, :adult, :tag_list)
    end
  end


end

app/controllers/shop/events_controller.rb
module Shop
  class EventsController < ShopController

    # GET /events
    # GET /events.json
    def index
      @events = Event.all.list_for(params[:page], params[:tag])
      @archives = Event.all.archive_for(params[:page], params[:tag])
    end

    # GET /events/1
    # GET /events/1.json
    def show
      @event = Event.find(params[:id])
    end
    
  end
end

app/controllers/shop/pages_controller.rb
module Shop
  class PagesController < ShopController

    def about
    end

    def contact
    end

  end
end

app/controllers/shop/posts_controller.rb
module Shop
  class PostsController < ShopController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end
  end
end

app/controllers/shop/starts_controller.rb
module Shop
  class StartsController < ShopController

    # GET /starts
    # GET /starts.json
    def index
      @starts = Start.all
    end

    # GET /starts/1
    # GET /starts/1.json
    def show
    end

  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/shop/events/_event.html.erb
<div class='col-sm-6 col-lg-4'>
  <div class="card">
    <%= link_to event do %>
      <div class="card-topper" style='background-image: url(<%= event.event_picture_url %>);'></div>
    <% end %>
    <div class="card-block">
      <h4 class="card-title"><%= link_to event.name, event %></h4>
      <p class='tags'><%= raw event.tags.map {|t| link_to t.name, events_path(tag: t.name)}.join(', ') %></p>
      <div class="row">
        <div class="col-lg-6">
          <% if (I18n.l event.date, :format => "%Y-%m-%d").to_s == Date.current.to_s %>
            <span class='tags'>Cena: <%= number_to_currency(event.price * 1.2, unit: "zł", separator: ",", delimiter: "", format: "%n %u") %></span>
          <% else %>
            <span class='tags'>Cena: <%= number_to_currency(event.price, unit: "zł", separator: ",", delimiter: "", format: "%n %u") %></span>
          <% end %>
        </div>
        <div class="col-lg-6">
          <span class='tags'>
            Dla dorosłych:
            <% if event.adult? %>
              Tak
            <% else %>
              Nie
            <% end %>
          </span>
        </div>
      </div>

      <h6 class="published-date">Data: <%= I18n.l event.date, :format => "%d-%m-%Y %H:%M" %></h6>
      <%= link_to event do %>
        <p class="card-text"><%= truncate(event.description.html_safe, length: 100) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shop/events/index.html.erb
<% provide(:page_title, 'Wydarzenia') %>
<% provide(:events_active, 'active') %>

<div class="row">
  <div class="col-md-3">
    <div class="row settings-space">
      <ul id="tabsJustified" class="nav nav-tabs">
        <li class="nav-item">
          <a href="" data-target="#events" data-toggle="tab" class="nav-link small text-uppercase active">Wydarzenia</a>
        </li>
        <% if current_author && current_author.admin? %>
          <li class="nav-item">
            <a href="" data-target="#archives" data-toggle="tab" class="nav-link small text-uppercase">Archiwum</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-2">
    <div class="input-group date picker">
      <input type="text" data-provide='datepicker' placeholder="Podaj date">
      <div class="input-group-addon">
        <span class="fa fa-calendar-check-o"></span>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="Podaj nazwe wydarzenia" aria-label="Wszukaj Wydarzenia" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary btn-pointer" type="button">Szukaj</button>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div id="tabsJustifiedContent" class="tab-content">
    <div id="events" class="tab-pane fade active active show">
      <div class="row">
        <%= render @events %>
      </div>
      <div class="apple_pagination">
        <div class="col-xl-12">
          <%= will_paginate @events, container: false %>
        </div>
      </div>
    </div>
    <div id="archives" class="tab-pane fade">
      <div class="row">
        <%= render @archives %>
      </div>
      <div class="apple_pagination">
        <div class="col-xl-12">
          <%= will_paginate @archives, container: false %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shop/events/show.html.erb
<% provide(:page_title, @event.name) %>
<% provide(:events_active, 'active') %>
<% %>

<script>
  $(document).ready(function () {
    var count = 0;


    $("#increase").click(function () {
      count++;
      if (count >= 0 && count < 5) {
        $('#decrease').attr("disabled", false);
        $('#increase').attr("disabled", false);
        $('#buyTicket').attr("disabled", false);
      } else {
        $('#increase').attr("disabled", true);
        count = 5;
      }


      $("#counter").val(count + " szt.");
    });

    $("#decrease").click(function () {
      count--;
      if (count > 0 && count <= 5) {
        $('#decrease').attr("disabled", false);
        $('#increase').attr("disabled", false)
      } else {
        $('#decrease').attr("disabled", true);
        $('#buyTicket').attr("disabled", true);
        count = 0;
      }
      $("#counter").val(count + " szt.");
    });

    $(function () {
      $('[data-toggle="tooltip"]').tooltip();
      $('[data-toggle="tooltip-birth-nil"]').tooltip('show');
      $('[data-toggle="tooltip-warn"]').tooltip('show');
    })
  });
</script>

<div class="row event-title">
  <div class="col-md-4">
    <img class="img-fluid" src=<%= @event.event_picture_url %>/>
  </div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-12">
        <h5>BILETY NA WYDARZENIE</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h2><%= @event.name.upcase %></h2>
      </div>
    </div>
  </div>
</div>
<div class="row event-content">
  <div class="col-md-8">
    <div class="row">
      <h5>OPIS</h5>
    </div>
    <div class="row">
      <span class="event-description"><%= @event.description %></span>
    </div>
  </div>
  <div class="col-md-4">
    <div class="row">
      <h5>PODSUMOWANIE</h5>
    </div>
    <div class="row">
      <h6>TERMIN</h6>
    </div>
    <div class="row">
      <span class="event-summary"><%= I18n.l @event.date, :format => "%d-%m-%Y %H:%M" %></span>
    </div>
    <div class="row">
      <h6>ADRES</h6>
    </div>
    <div class="row">
      <span class="event-summary"><%= @event.address %></span>
    </div>
    <div class="row">
      <h6>CENA</h6>
    </div>
    <div class="row">
      <span class="event-summary"><%= number_to_currency(@event.price, unit: "zł", separator: ",", delimiter: "", format: "%n %u") %>
        <span class="event-day-info">(w dniu wydarzenia <span class="event-day-info-price"><%= number_to_currency(@event.price * 1.2, unit: "zł", separator: ",", delimiter: "", format: "%n %u") %></span>)</span></span>
    </div>
    <div class="row">
      <h6>ILOŚĆ MIEJSC</h6>
    </div>
    <div class="row event-quantity" style="<%= 'background-color: #e1ffde' if @event.quantity > 10 %>">
      <div class="col-md-12">
        <div class="row">
      <span style="margin-top: -7px">Dostępna do wyczerpania,
        najpóźniej do</span>
        </div>
        <div class="row">
          <span><%= I18n.l @event.date, :format => "%d-%m-%Y %H:%M" %></span>
        </div>
        <div class="row">
          <span style="margin-bottom: 10px">Dostępne <%= @event.quantity %> miejsc</span>
        </div>
      </div>
    </div>
    <div class="row">
      <h6>DLA DOROSŁYCH</h6>
    </div>
    <div class="row">
      <span class="event-summary"><% if @event.adult? %>
              Tak
            <% else %>
              Nie
            <% end %>
      </span>
    </div>
    <div class="row">
      <h6>ILOŚĆ SZTUK</h6>
    </div>
    <% if @event.quantity != 0 %>
      <div class="row">

        <div class="col-md-4">
          <div class="test"></div>
          <input id="counter" type="text" class="form-control" id="quantity" aria-describedby="quantity" value="0 szt." placeholder="0 szt." disabled="true">
        </div>
        <div class="col-md-4">
          <button id="decrease" class="btn btn-danger btn-max btn-pointer" disabled="true">-</button>
        </div>
        <div class="col-md-4">
          <button id="increase" class="btn btn-success btn-max btn-pointer">+</button>
        </div>
      </div>
    <% end %>
    <div class="row">
      <% if ((Date.new(@event.date.year, @event.date.mon, @event.date.day).yday) - (Date.current.yday) <= 31 && (Date.new(@event.date.year, @event.date.mon, @event.date.day).yday) - (Date.current.yday) >= 0) %>
        <% if @event.quantity != 0 %>
          <% if !author_signed_in? %>
            <%= link_to 'Zaloguj się, aby kupić bilet', author_session_path, class: "btn btn-warning btn-buy btn-max btn-pointer" %>
          <% else %>
            <% if current_author.birth_date %>
              <% if @event.adult && (Date.current.year - (I18n.l current_author.birth_date, :format => "%Y").to_i) >= 18 %>
                <%= button_to 'Kup bilet na wydarzenie', authors_summary_path,
                              params: {body: 'super test', event_id: @event, event_name: @event.name,
                                       event_description: @event.description, event_address: @event.address,
                                       event_date: @event.date, event_picture: @event.event_picture_url, user_id: current_author.id, event_price: @event.price, ticket_counter: 1}, method: :post, class: "btn btn-success btn-buy btn-max btn-pointer" %>
              <% elsif @event.adult && (Date.current.year - (I18n.l current_author.birth_date, :format => "%Y").to_i) < 18 %>
                <button id="warnTicket" class="btn btn-warning btn-buy btn-max btn-pointer" data-placement="bottom" title="Nie masz wystarczającej ilości lat" data-toggle="tooltip-warn">KUP
                  BILET
                </button>
              <% else %>
                <%= button_to 'Kup bilet na wydarzenie', authors_summary_path,
                              params: {body: 'super test', event_id: @event, event_name: @event.name,
                                       event_description: @event.description, event_address: @event.address,
                                       event_date: @event.date, event_picture: @event.event_picture_url, user_id: current_author.id, event_price: @event.price, ticket_counter: 1}, method: :post, class: "btn btn-success btn-buy btn-max btn-pointer" %>
              <% end %>
            <% end %>
            <% if current_author.birth_date == nil %>
              <%= link_to 'Ustaw date urodzenia', authors_account_path, class: "btn btn-danger btn-buy btn-max btn-pointer" %>
            <% end %>
          <% end %>
        <% else %>
          <h3 class="lack-ticket">Brak biletów na wydarzenie</h3>
        <% end %>
      <% elsif ((Date.new(@event.date.year, @event.date.mon, @event.date.day).yday) - (Date.current.yday) < 0) %>
        <span>Wydarzenie już się odbyło!</span>
      <% else %>
        <span>Bilety będą dostępne w sprzedaży od dnia</span>
        <span><%= I18n.l @event.date.prev_month(), :format => "%d-%m-%Y" %></span>
      <% end %>


    </div>
  </div>
</div>