config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root :to => "shop/starts#index"

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account

    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    put '/add_money' => 'accounts#add_money', as: :add_money
    post 'ticket_return' => '/authors/tickets#ticket_return', as: :ticket_return
    post '/tickets/summary' => 'tickets#buy', as: :summary
    post '/buy' => 'tickets#index', as: :buy
    post '/return_all' => '/authors/tickets#return_all', as: :return_all
    get '/returns' => 'tickets#returns', as: :returns
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
    resources :tickets
    resources :starts
    resources :events
  end

  scope module: 'shop' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'starts' => 'starts#index', as: :starts
    get 'events' => 'events#index', as: :events
    get 'events/:id' => 'events#show', as: :event
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/start.rb
class Start < ApplicationRecord
end

app/controllers/authors/starts_controller.rb
module Authors
  class StartsController < AuthorController
    before_action :set_start, only: [:show, :edit, :update, :destroy]

    # GET /starts
    # GET /starts.json
    def index
      @starts = Start.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /starts/1
    # GET /starts/1.json
    def show
    end

    # GET /starts/new
    def new
      @start = Start.new
    end

    # GET /starts/1/edit
    def edit
    end

    # POST /starts
    # POST /starts.json
    def create
      @start = Start.new(start_params)

      respond_to do |format|
        if @start.save
          format.html {redirect_to authors_start_path(@start), notice: 'Post was successfully created.'}
          format.json {render :show, status: :created, location: @start}
        else
          format.html {render :new}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /starts/1
    # PATCH/PUT /starts/1.json
    def update
      respond_to do |format|
        if @start.update(start_params)
          format.html {redirect_to authors_start_path(@start), notice: 'Start was successfully updated.'}
          format.json {render :show, status: :ok, location: @start}
        else
          format.html {render :edit}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /starts/1
    # DELETE /starts/1.json
    def destroy
      @start.destroy
      respond_to do |format|
        format.html {redirect_to authors_start_path, notice: 'Start was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_start
      @start = Start.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def start_params
      params.require(:start).permit(:picture_url, :title, :features)
    end
  end
end

app/controllers/shop/events_controller.rb
module Shop
  class EventsController < ShopController

    # GET /events
    # GET /events.json
    def index
      @events = Event.all.list_for(params[:page], params[:tag])
      @archives = Event.all.archive_for(params[:page], params[:tag])
    end

    # GET /events/1
    # GET /events/1.json
    def show
      @event = Event.find(params[:id])
    end
    
  end
end

app/controllers/shop/pages_controller.rb
module Shop
  class PagesController < ShopController

    def about
    end

    def contact
    end

  end
end

app/controllers/shop/posts_controller.rb
module Shop
  class PostsController < ShopController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end
  end
end

app/controllers/shop/starts_controller.rb
module Shop
  class StartsController < ShopController

    # GET /starts
    # GET /starts.json
    def index
      @starts = Start.all
    end

    # GET /starts/1
    # GET /starts/1.json
    def show
    end

  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/shop/starts/_start.html.erb
<div class="parallax-image" style="background-image: url(<%= start.picture_url %>)">
  <h1 class="parallax-center">
    <%= start.title.upcase %> <br>
    <% if start.features == "news" %>
      <%= link_to 'SPRAWDŹ', posts_path, class: "btn btn-outline-light btn-pointer" %>
    <% elsif start.features == "events" %>
      <%= link_to 'PRZEGLĄDAJ', events_path, class: "btn btn-outline-light btn-pointer" %>
    <% elsif start.features == "join" %>
      <% if !author_signed_in? %>
        <%= link_to 'ZAREJESTRUJ SIĘ', new_author_registration_path, class: "btn btn-light btn-pointer" %>
        /
        <%= link_to 'ZALOGUJ', author_session_path, class: "btn btn-outline-light btn-pointer" %>
      <% else %>
        <%= link_to current_author.name, posts_path, class: "btn btn-outline-light btn-pointer" %>
      <% end %>
    <% elsif start.features == "search" %>
      <div class="test">
        <input class="form-control centered" type="text" placeholder="Szukaj">
      </div>
    <% end %>
  </h1>
</div>

app/views/shop/starts/index.html.erb
<% provide(:page_title, 'Strona główna') %>

<%= render @starts %>

app/views/shop/starts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture url:</strong>
  <%= @start.picture_url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @start.title %>
</p>

<%= link_to 'Edit', edit_start_path(@start) %> |
<%= link_to 'Back', starts_path %>