config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root :to => "shop/starts#index"

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account

    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    put '/add_money' => 'accounts#add_money', as: :add_money
    post 'ticket_return' => '/authors/tickets#ticket_return', as: :ticket_return
    post '/tickets/summary' => 'tickets#buy', as: :summary
    post '/buy' => 'tickets#index', as: :buy
    post '/return_all' => '/authors/tickets#return_all', as: :return_all
    get '/returns' => 'tickets#returns', as: :returns
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
    resources :tickets
    resources :starts
    resources :events
  end

  scope module: 'shop' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    get 'starts' => 'starts#index', as: :starts
    get 'events' => 'events#index', as: :events
    get 'events/:id' => 'events#show', as: :event
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :tickets

  validates_presence_of :name, on: :update

  def change_password(attrs)
    update(password: attrs[:new_password], password_confirmation: attrs[:new_password_confirmation])
  end

  def gravatar_image_url
    "https://www.gravatar.com/avatar/#{gravatar_hash}"
  end

  def display_name
    if name.present?
      name
    else
      "Moje konto"
    end
  end

  private

  def gravatar_hash
    Digest::MD5.hexdigest(email.downcase)
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  description      :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  author_id        :integer
#  published        :boolean          default(FALSE)
#  published_at     :datetime
#

class Post < ApplicationRecord

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author, :optional => true

  PER_PAGE = 3

  scope :most_recent, -> {order(published_at: :desc)}
  scope :published, -> {where(published: true)}
  scope :recent_paginated, -> (page) { most_recent.paginate(page: page, per_page: PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  def display_day_published
    if published_at.present?
      "Opublikowano #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Jeszcze, nie opublikowano."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end
end

app/controllers/author/posts_controller.rb
module Author
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    # GET /posts.json
    def index                               
      @posts = Post.all
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url)
    end
  end


end

app/controllers/author/tickets_controller.rb
module Author
  class TicketsController < AuthorController
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]

    # GET /tickets
    # GET /tickets.json
    def index
      @tickets = Ticket.most_recent
    end

    # GET /tickets/1
    # GET /tickets/1.json
    def show
    end

    # GET /tickets/new
    def new
      @ticket = Ticket.new
    end

    # GET /tickets/1/edit
    def edit
    end

    # POST /tickets
    # POST /tickets.json
    def create
      @ticket = Ticket.new(ticket_params)

      respond_to do |format|
        if @ticket.save
          format.html {redirect_to @ticket, notice: 'Ticket was successfully created.'}
          format.json {render :show, status: :created, location: @ticket}
        else
          format.html {render :new}
          format.json {render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /tickets/1
    # PATCH/PUT /tickets/1.json
    def update
      respond_to do |format|
        if @ticket.update(ticket_params)
          format.html {redirect_to @ticket, notice: 'Ticket was successfully updated.'}
          format.json {render :show, status: :ok, location: @ticket}
        else
          format.html {render :edit}
          format.json {render json: @ticket.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /tickets/1
    # DELETE /tickets/1.json
    def destroy
      @ticket.destroy
      respond_to do |format|
        format.html {redirect_to tickets_url, notice: 'Ticket was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :picture_url)
    end
  end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController

  before_action :authenticate_author!
  before_action :ensure_admin_user!

  def ensure_admin_user!
    if !current_author.admin? and (request.path.start_with?('/authors/posts') or request.path.start_with?('/authors/starts') or request.path.start_with?('/authors/events'))
      redirect_to root_path
    end
  end
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit

    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Successfully saved info.'
      else
        flash[:danger] = current_author.display_error_messages
      end
      redirect_to authors_account_path
    end

    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.change_password(author_password_params)
          sign_in(author, bypass: true)
          flash[:success] = 'Successfully changed password.'
        else
          flash[:danger] = author.display_error_messages
        end
      else
        flash[:danger] = 'Current password was incorrect.'
      end
      redirect_to authors_account_path
    end

    def add_money
      amount = params[:amount]
      author = current_author
      author.money = author.money + Integer(amount)
      author.save()
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:name, :email, :bio, :birth_date)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
  end
end

app/controllers/authors/events_controller.rb
module Authors
  class EventsController < AuthorController
    before_action :set_event, only: [:show, :edit, :update, :destroy]

    # GET /events
    # GET /events.json
    def index
      @events = Event.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /events/1
    # GET /events/1.json
    def show
    end

    # GET /events/new
    def new
      @event = Event.new
    end

    # GET /events/1/edit
    def edit
    end

    # POST /events
    # POST /events.json
    def create
      @event = Event.new(event_params)

      respond_to do |format|
        if @event.save
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully created.'}
          format.json {render :show, status: :created, location: @event}
        else
          format.html {render :new}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /events/1
    # PATCH/PUT /events/1.json
    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html {redirect_to authors_event_path(@event), notice: 'Event was successfully updated.'}
          format.json {render :show, status: :ok, location: @event}
        else
          format.html {render :edit}
          format.json {render json: @event.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /events/1
    # DELETE /events/1.json
    def destroy
      @event.destroy
      respond_to do |format|
        format.html {redirect_to authors_event_path, notice: 'Event was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :address, :price, :description, :date, :quantity , :event_picture_url, :adult, :tag_list)
    end
  end


end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html {redirect_to authors_post_path(@post), notice: 'Post was successfully created.'}
          format.json {render :show, status: :created, location: @post}
        else
          format.html {render :new}
          format.json {render json: @post.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html {redirect_to authors_post_path(@post), notice: 'Post was successfully updated.'}
          format.json {render :show, status: :ok, location: @post}
        else
          format.html {render :edit}
          format.json {render json: @post.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html {redirect_to authors_post_path, notice: 'Post was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description, :banner_image_url, :tag_list)
    end
  end


end

app/controllers/authors/starts_controller.rb
module Authors
  class StartsController < AuthorController
    before_action :set_start, only: [:show, :edit, :update, :destroy]

    # GET /starts
    # GET /starts.json
    def index
      @starts = Start.all.paginate(:page => params[:page], per_page: 5)
    end

    # GET /starts/1
    # GET /starts/1.json
    def show
    end

    # GET /starts/new
    def new
      @start = Start.new
    end

    # GET /starts/1/edit
    def edit
    end

    # POST /starts
    # POST /starts.json
    def create
      @start = Start.new(start_params)

      respond_to do |format|
        if @start.save
          format.html {redirect_to authors_start_path(@start), notice: 'Post was successfully created.'}
          format.json {render :show, status: :created, location: @start}
        else
          format.html {render :new}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /starts/1
    # PATCH/PUT /starts/1.json
    def update
      respond_to do |format|
        if @start.update(start_params)
          format.html {redirect_to authors_start_path(@start), notice: 'Start was successfully updated.'}
          format.json {render :show, status: :ok, location: @start}
        else
          format.html {render :edit}
          format.json {render json: @start.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /starts/1
    # DELETE /starts/1.json
    def destroy
      @start.destroy
      respond_to do |format|
        format.html {redirect_to authors_start_path, notice: 'Start was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_start
      @start = Start.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def start_params
      params.require(:start).permit(:picture_url, :title, :features)
    end
  end
end

app/controllers/shop/posts_controller.rb
module Shop
  class PostsController < ShopController

    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">

      <div class="card">
        <div class="card-block">
          <% if @post.new_record? %>
            <h4 class="card-title">Nowy artukuł</h4>
          <% else %>
            <h4 class="card-title">
              <b>Edytuj </b>
              <span class="thin-text"><%= @post.title %></span>
            </h4>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tytuł' %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'URL obrazu' %>
              <%= f.text_field :banner_image_url, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Opis' %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label 'Tagi' %>
              <%= f.text_area :tag_list, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="actions">
              <%= f.submit "Zapisz", class: 'btn btn-success btn-block btn-pointer' %>
            </div>
          </li>
        </ul>
      </div>

      <% if @post.persisted? %>
        <%= link_to 'Pokaż', @post %> |
      <% end %>
      <%= link_to 'Wróć', authors_posts_path %>

    </div>
    <div class="col-md-8">

      <div class="field">
        <%= f.text_area :body %>
      </div>
    </div>
  </div>

<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td><%= link_to post.title, authors_post_path(post) %></td>
  <td></td>
  <% if post.published? %>
    <td><%= link_to 'Ukryj', unpublish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-primary' %></td>
  <% else %>
    <td><%= link_to 'Opublikuj', publish_authors_post_path(post), method: :put, class: 'btn btn-sm btn-success' %></td>
  <% end %>
  <td><%= link_to 'Edytuj', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
  <td><%= link_to 'Usuń', authors_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edytuj #{@post.title}") %>
<% provide(:post_active, 'active') %>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'Twoje artykuły') %>
<% provide(:author_post_active, 'active') %>


<div class="row">
  <div class="space">
    <%= link_to 'Nowy artykuł', new_authors_post_path, class: 'btn btn-primary' %>
  </div>
  <table class="table table-striped">
    <tr>
      <th colspan="5">
        Tytuł
      </th>
    </tr>
    <%= render @posts %>
  </table>
</div>
<div class="apple_pagination">
  <%= will_paginate @posts, container: false %>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'Nowy artykuł') %>
<% provide(:post_active, 'active') %>

<%= render 'form', post: @post, url: authors_posts_url %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
  <%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
  <%= link_to 'Remove', authors_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-xs-center">
    <h1><%= @post.title %></h1>
    <p><%= @post.display_day_published %></p>
    <%= @post.body.html_safe %>
  </div>
</div>